//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Student
    {
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Description { get; set; }
    }
}
